import '../styles/components.css';
import '../styles/tokens.css';
import '@/styles/brand.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/TopNav";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: { icon: '/brand/favicon.svg', apple: '/brand/apple-touch-icon.png' }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-ssr-beta="true">
      <body className={`${inter.variable} antialiased grid-container`} data-ssr-beta="true">
        <TopNav />
        {children}
        {/* SSR beta marker for monitors */}
        <div data-ssr-beta="true" style={{ display: 'none' }}>BETA</div>
      </body>
    </html>
  );
}
